### ISSUE TITLE
traceback when printing info on a 11.0 mar

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla/build-mar#42]
```
➜  tmp mar -T firefox-10.0.2-11.0.partial.mar 
Traceback (most recent call last):
  File "/home/bhearsum/.virtualenvs/pip3/bin/mar", line 11, in <module>
    sys.exit(main())
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/mardor/cli.py", line 190, in main
    print("\n".join(do_list(args.list_detailed, detailed=True)))
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/mardor/cli.py", line 113, in do_list
    with MarReader(f) as m:
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/mardor/reader.py", line 50, in __init__
    self.mardata = mar.parse_stream(self.fileobj)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 3593, in _parse
    return sc._parsereport(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 2222, in _parse
    e = self.subcon._parsereport(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/bhearsum/.virtualenvs/pip3/lib/python3.6/site-packages/construct/core.py", line 3487, in _parse
    raise SelectError("no subconstruct matched")
construct.core.SelectError: no subconstruct matched

```

10.0 and 12.0 seem fine.

**Comment by catlee** [comment]
Which version of mardor are you using? Trying this on master on my machine causes python to suck up all my RAM and then crash :)

**Comment by catlee** [comment]
I figured out the cause. Firefox 11 mar files had no product information block in them.

**Comment by mozbhearsum** [comment]
I was on 2.2.3.
