### ISSUE TITLE
ImportError: cannot import name lzma

### ISSUE THREAD

**Issue by wellington1993** [mozilla/build-mar#54]
i''ve got this error:

```python
Traceback (most recent call last):
  File "/home/wellington/.local/bin/mar", line 6, in <module>
    from mardor.cli import main
  File "/home/wellington/.local/lib/python2.7/site-packages/mardor/cli.py", line 14, in <module>
    from mardor.reader import MarReader
  File "/home/wellington/.local/lib/python2.7/site-packages/mardor/reader.py", line 13, in <module>
    from mardor.signing import get_signature_data
  File "/home/wellington/.local/lib/python2.7/site-packages/mardor/signing.py", line 17, in <module>
    from mardor.utils import file_iter
  File "/home/wellington/.local/lib/python2.7/site-packages/mardor/utils.py", line 13, in <module>
    from backports import lzma
ImportError: cannot import name lzma
```

How to solve?

Thanks!

**Comment by wellington1993** [comment]
Temporary solved changing(commenting):

```python
#if six.PY2:
#    from backports import lzma
#else:
import lzma
```
in ```~/.local/lib/python2.7/site-packages/mardor/utils.py```

Thanks!

**Comment by catlee** [comment]
Can you tell me where your lzma package comes from? It's not typically provided as part of a standard python 2.7 distribution.

**Comment by wellington1993** [comment]
@catlee Sure, I found here:
```
<module 'lzma' from '/usr/lib/python2.7/dist-packages/lzma.x86_64-linux-gnu.so'>
```

**Comment by wellington1993** [comment]
Appears to be deb depedency from one off my installed software:
https://packages.ubuntu.com/bionic/amd64/python-lzma/filelist

**Comment by wellington1993** [comment]
For example:
torbrowser-launcher 
(https://ubuntu.pkgs.org/16.04/ubuntu-universe-amd64/python-lzma_0.5.3-3_amd64.deb.html)
